### PR TITLE
deps: segregate third-party deps to deps.ts file

### PR DESCRIPTION
**Pull request by ayntee**

### CODE REVIEW

**Comment by DjDeveloperr** [comment]
Looks good! Linter is failing though.

**Comment by adolphin-hitler** [comment]
> Looks good! Linter is failing though.
Lint errors be like:
never gonna give you up 
never gonna let you down
never gonna run around and desert you
never gonna make you cry
never gonna say goodbye

**Review by Helloyunho — APPROVED** [review]
Actually I thought this will make code even yucky but it looks better 🤣

**Review by AkiaCode — APPROVED** [review]

**Comment by DjDeveloperr** [comment]
LGTM

**Pull request merged**
