### PR TITLE
Add `addReaction` and `removeReaction` feature, Handle null-id emojis

### PR DESCRIPTION
**Pull request by Helloyunho**
This PR adds `addReaction` and `removeReaction` feature, and makes the lib handle null-id emojis(default emojis).

### CODE REVIEW

**Review by AkiaCode — APPROVED** [review]

**Comment by DjDeveloperr** [comment]
I think it's going to be inconsistent if we just put name in place of ID if its null, IDs are Snowflakes all over and there could be users assuming they can be serialized for more info like created at, this will likely error it.

**Comment by Helloyunho** [comment]
> I think it's going to be inconsistent if we just put name in place of ID if its null, IDs are Snowflakes all over and there could be users assuming they can be serialized for more info like created at, this will likely error it.

hmm, but there're no other ways to fix it I think..?

**Comment by DjDeveloperr** [comment]
I think it being nullable should be fine. We aren't supposed to cache default emojis, so we don't need their name as ID either. Something user should handle themselves if necessary.

**Comment by Helloyunho** [comment]
> I think it being nullable should be fine. We aren't supposed to cache default emojis, so we don't need their name as ID either. Something user should handle themselves if necessary.

Okay, then I'll make it to skip caching if its id is null

**Comment by Helloyunho** [comment]
image
And also I found that Emoji's name also can be null

**Pull request merged**
