### PR TITLE
change Message.mentions to User[] 

### PR DESCRIPTION
**Pull request by Preta-Crowz**
Other mentions types are already exist as property but user was not.
So I changed mentions property to reference users directly.

+ Also fix issue that user mentions aren't saved to mentions list

### CODE REVIEW

**Comment by Preta-Crowz** [comment]
🤦 MessageMentions is useless after change but I forgot to remove it

**Comment by Helloyunho** [comment]
What about channel mentions and role mentions? The reason why we made `messageMentions` is to merge them in one.

**Comment by Preta-Crowz** [comment]
> What about channel mentions and role mentions? The reason why we made `messageMentions` is to merge them in one.

these two are already exist as mentionRoles / mentionChannels
also, messageMentions is not working to users and roles.
image

**Comment by Helloyunho** [comment]
> these two are already exist as mentionRoles / mentionChannels

Oh wow, I didn't notice it actually.

> also, messageMentions is not working to users and roles.

Hmm, it should work. I think I should investigate more.

**Comment by Helloyunho** [comment]
> > also, messageMentions is not working to users and roles.
> 
> Hmm, it should work. I think I should investigate more.

I tested it, and it works as it's intended.

**Comment by Preta-Crowz** [comment]
> 
> 
> > > also, messageMentions is not working to users and roles.
> > 
> > 
> > Hmm, it should work. I think I should investigate more.
> 
> I tested it, and it works as it's intended.

then why my code is not working 🤔

**Comment by Preta-Crowz** [comment]
tested again and it works this time 🤔

**Comment by Preta-Crowz** [comment]
I got it. JSON.stringify doesn't return anything 🤦

**Comment by DjDeveloperr** [comment]
> 
> 
> I got it. JSON.stringify doesn't return anything 🤦

I think it's due to Collection not being serialized properly in JSON.stringify.

**Pull request closed without merging**
