### PR TITLE
feat: add template structure and methods

### PR DESCRIPTION
**Pull request by ayntee**
- Added Template structure
- Added helper methods to the template structure
- Updated the Template Discord API types

### CODE REVIEW

**Comment by AkiaCode** [comment]
image

**Comment by DjDeveloperr** [comment]
I think the first words upper case will look better (JSDoc)

image

**Comment by ayntee** [comment]
> I think the first words upper case will look better (JSDoc)
> 
> image

Copied it from Discord API docs, this shouldn't really matter much...
image

**Comment by DjDeveloperr** [comment]
Yes but just a suggestion as it looks cleaner in docs.

**Review by Helloyunho — APPROVED** [review]
UPDATE: It was not code template, my bad

Anyway, nice work!

**Comment by DjDeveloperr** [comment]
LGTM

**Pull request merged**
